---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zino Lath.
--- DateTime: 16/07/2021 10:50
---

function Interpolate(a,b,x)
    return a + (b - a) * x
end

function EaseOutCubic(x)
    return 1 - (1-x)^3;
end
local c1 = 1.70158
local c2 = c1 * 1.525
function EaseInOutBack(x)
    return ternary(x < 0.5, (math.pow(2 * x, 2) * ((c2 + 1) * 2 * x - c2)) / 2,
    (math.pow(2 * x - 2, 2) * ((c2 + 1) * (x * 2 - 2) + c2) + 2) / 2)
end
function EaseInQuart(x)
    return x*x*x*x
end
function Linear(x)
    return x
end

local Lin = Linear
local ternary_ = ternary
local Int = Interpolate
function Interpolate_Element(arr, t, func)
    local src = arr[int(t)] --get the first value for lerp
    local did = ternary_(int(t + 1) > #arr, int(t + 1 - #arr), int(t + 1)) -- loops through the array
    local dest = arr[did] --get the second index for lerp
    local _t = t - int(t)
    func = func or Lin
    return Int(src,dest,func(_t))
end
function clamp(n,_min,_max)
    return max(min(n,_max),_min)
end